// Collect the licences of everything Shelf ships and write THIRD-PARTY-NOTICES.md.
//
//   npm run licenses
//
// Walks the production dependencies of the app, the server and the client
// (the client's code is bundled into the app, so its libraries ship too),
// reads each package's licence text, and adds the pieces that are not npm
// packages: Electron's own runtime, the bundled ffprobe build and the fonts.
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'THIRD-PARTY-NOTICES.md');
const LICENSE_FILES = /^(licen[cs]e|copying|notice)(\.|$)/i;

const seen = new Map();

function readPkg(dir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  } catch {
    return null;
  }
}

/** node_modules folder holding `name`, searched upward like Node does. */
function resolvePkgDir(name, fromDir) {
  let dir = fromDir;
  for (;;) {
    const candidate = path.join(dir, 'node_modules', name);
    if (fs.existsSync(path.join(candidate, 'package.json'))) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function licenseText(dir) {
  const file = fs.readdirSync(dir).find((f) => LICENSE_FILES.test(f));
  if (!file) return null;
  const text = fs.readFileSync(path.join(dir, file), 'utf8').trim();
  return text.length > 20_000 ? `${text.slice(0, 20_000)}\n… (truncated; see the package)` : text;
}

function collect(name, fromDir) {
  const dir = resolvePkgDir(name, fromDir);
  if (!dir) return;
  const pkg = readPkg(dir);
  if (!pkg) return;
  const key = `${pkg.name}@${pkg.version}`;
  if (seen.has(key)) return;
  seen.set(key, {
    name: pkg.name,
    version: pkg.version,
    license: typeof pkg.license === 'string' ? pkg.license : pkg.license?.type || 'see text',
    homepage: pkg.homepage || (typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url) || '',
    text: licenseText(dir),
  });
  for (const dep of Object.keys(pkg.dependencies || {})) collect(dep, dir);
}

for (const base of [ROOT, path.join(ROOT, 'server'), path.join(ROOT, 'client')]) {
  const pkg = readPkg(base);
  if (!pkg) continue;
  const names = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.optionalDependencies || {}),
    // The client's libraries are compiled into the app that ships.
    ...(base.endsWith('client') ? Object.keys(pkg.devDependencies || {}).filter((d) => /^(react|@fontsource|tailwind)/.test(d)) : []),
  ];
  for (const name of names) collect(name, base);
}

const packages = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
const counts = packages.reduce((acc, p) => ({ ...acc, [p.license]: (acc[p.license] || 0) + 1 }), {});

const head = `# Third-party notices

Shelf itself is MIT licensed (see LICENSE). It ships the software below, each
under its own licence. Nothing here is modified unless noted.

Generated by \`npm run licenses\` on ${new Date().toISOString().slice(0, 10)}.

## Summary

${Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([l, n]) => `- ${l}: ${n} package${n === 1 ? '' : 's'}`).join('\n')}

## FFmpeg (ffprobe), GPL-3.0

The Windows build of Shelf includes \`ffprobe.exe\` from the FFmpeg project
(gyan.dev "essentials" build, configured with \`--enable-gpl --enable-version3\`).
It is a separate program that Shelf runs to read a video file's resolution,
length and languages; Shelf does not link against it.

ffprobe is licensed under the GNU General Public License version 3 (see
\`licenses/GPL-3.0.txt\`). Its complete corresponding source is published by the
FFmpeg project at <https://ffmpeg.org/download.html> and by the build's author at
<https://www.gyan.dev/ffmpeg/builds/>. On request, the maintainer of Shelf will
also provide the source used for the bundled build.

To build Shelf without it, remove the \`@ffprobe-installer/win32-x64\` optional
dependency: everything except the file-details feature works unchanged.

## Electron and Node.js

The desktop app is built on Electron (MIT), which embeds Chromium (BSD-3-Clause
and others) and Node.js (MIT). Their full notices are listed in the
\`LICENSES.chromium.html\` file installed beside the app.

## Fonts

Archivo and IBM Plex Sans/Mono are licensed under the SIL Open Font License 1.1.
The fonts may be used and redistributed with this software, but not sold on their
own. See the \`@fontsource\` packages below for the licence text.

## Services

Shelf talks to these only when you add your own key or account:

- **TMDB** — This product uses the TMDB API but is not endorsed or certified by
  TMDB. The free API licence covers personal, non-commercial use.
- **OpenSubtitles** — subtitles are searched and downloaded under your own
  OpenSubtitles account and its daily limits.
- **Trakt** — sync uses your own Trakt API application and account.

## Packages

`;

const body = packages
  .map((p) => {
    const link = p.homepage.replace(/^git\+|\.git$/g, '');
    return `### ${p.name} ${p.version}\n\n${p.license}${link ? ` · <${link}>` : ''}\n\n${
      p.text ? `<details><summary>Licence text</summary>\n\n\`\`\`\n${p.text}\n\`\`\`\n\n</details>` : '_No licence file in the package._'
    }\n`;
  })
  .join('\n');

fs.writeFileSync(OUT, head + body);
console.log(`THIRD-PARTY-NOTICES.md -> ${packages.length} packages`);
